### ISSUE TITLE
TestCluster is !Send in v0.4.0, preventing shared cluster patterns

### ISSUE THREAD

**Issue by leynos** [leynos/pg-embedded-setup-unpriv#84]
## Summary

In v0.4.0, `TestCluster` became `!Send` due to the `ScopedEnv` component containing `PhantomData<Rc<()>>`. This prevents using `TestCluster` in contexts that require `Send`, such as:

1. Shared cluster fixtures accessed across test threads
2. rstest fixtures with timeouts (which require `Send + 'static` closures)
3. Any cross-thread sharing patterns

While we've successfully worked around this with database templating, the `!Send` constraint limits architectural options for high-performance test suites.

### What Works ✅
- Per-test clusters (each test spawns its own cluster)
- Template-based database cloning (95-99% faster than fresh migrations)
- All synchronous, single-threaded test patterns

### What's Blocked ❌
- Shared cluster across test threads using `OnceLock<TestCluster>`
- rstest fixtures with `RSTEST_TIMEOUT` set
- Async test patterns that move clusters between threads
- Any `Send`-bounded generic contexts

## Code Example

```rust
use std::sync::OnceLock;
use pg_embed_setup_unpriv::TestCluster;

// This worked in v0.1.0 but fails in v0.4.0:
static SHARED_CLUSTER: OnceLock<TestCluster> = OnceLock::new();

fn shared_cluster() -> Result<&'static TestCluster, Error> {
    SHARED_CLUSTER.get_or_try_init(|| {
        TestCluster::new()  // ❌ Error: TestCluster cannot be sent between threads safely
    })
}
```

Error message:

```text
error[E0277]: `Rc<()>` cannot be sent between threads safely
  --> src/lib.rs:5:5
   |
   | static SHARED_CLUSTER: OnceLock<TestCluster> = OnceLock::new();
   |        ^^^^^^^^^^^^^^ `Rc<()>` cannot be sent between threads safely
   |
   = help: within `TestCluster`, the trait `Send` is not implemented for `Rc<()>`
note: required because it appears within the type `PhantomData<Rc<()>>`
note: required because it appears within the type `ScopedEnv`
note: required because it appears within the type `TestCluster`
```

## Background

The !Send constraint appears to be intentional due to ScopedEnv manipulating process-global environment variables, which is inherently thread-unsafe. This is a sound decision for safety.

However, PostgreSQL clusters themselves are thread-safe once started (they're external processes). The environment manipulation happens during startup/shutdown, not during normal operation.

### Migration Path We Took

We successfully migrated to v0.4.0 by:

1. Disabling rstest timeouts for postgres tests (timeouts require Send)
2. Implementing template-based cloning for fast database creation
3. Per-test clusters instead of shared clusters

This works well and delivers 95-99% speedup via templates, but sacrifices the 20-30 second cluster bootstrap savings that a truly
shared cluster would provide.

## Questions for Maintainers

1. Is the !Send constraint intentional and permanent? Or is it an implementation detail that could potentially be addressed?
2. Could ScopedEnv be made Send by using thread-safe primitives for environment manipulation (e.g., Arc instead of Rc, mutexes for the environment state)?
3. Alternative architecture? Could cluster creation return a Send-safe handle while keeping environment manipulation isolated to
the creation thread?
4. Documented pattern? What's the recommended approach for high-performance test suites that want to amortize the cluster bootstrap cost across many tests?

## Potential Solutions (for discussion)

Option 1: Make ScopedEnv Send-safe

Replace PhantomData<Rc<()>> with PhantomData<Arc<()>> or remove the phantom marker if it's not strictly necessary. Protect
environment mutations with a Mutex or similar.

Trade-off: Slightly more complex synchronization, but enables shared cluster patterns.

Option 2: Separate lifecycle handle

Return a Send-able cluster handle from TestCluster::new() while keeping the !Send environment guard internal.

```rust
pub struct ClusterHandle { /* Send-safe */ }
pub struct ClusterGuard { /* !Send, manages env */ }

impl TestCluster {
    pub fn new() -> (ClusterHandle, ClusterGuard) { ... }
}
```

Trade-off: API complexity, but preserves safety while enabling sharing.

Option 3: Document as "not supported"

If the !Send constraint is fundamental and unchangeable, document that shared cluster patterns are not supported and template-based cloning is the recommended approach.

Trade-off: Simpler API, but limits architectural options.

Environment:

- pg-embed-setup-unpriv version: 0.4.0
- Use case: Test suite with 300+ database integration tests
- Platform: Linux x86_64

## References

Our migration implementation (using template-based approach):
- Database template creation for fast cloning
- Per-test clusters with template reuse
- 10-50ms per test after initial template creation

We're happy to help test any potential solutions or provide feedback on the recommended approach.

Thank you for this excellent library! The privilege-dropping and RAII patterns are fantastic, and v0.4.0's template database support is exactly what we needed.
